include:
  - docker-compose-dify.yaml

services:
  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: datagpt@datagpt.com
  #     PGADMIN_DEFAULT_PASSWORD: datagpt
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - ./volumes/pgadmin/data:/var/lib/pgadmin

  mockdb:
    image: postgres:15-alpine
    ports:
      - "5432:5432" #remove later
    environment:
      POSTGRES_USER: ${MOCKDB_USER:-datagpt}
      POSTGRES_PASSWORD: ${MOCKDB_PASSWORD:-datagpt}
      POSTGRES_DB: ${MOCKDB_DB:-datagpt}
    volumes:
      - ./volumes/mockdb/data:/var/lib/postgresql/data

  metallogic-api:
    image: yc3231996/metallogic-api:latest
    build:
      context: ../api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/metallogic/api/metastore:/app/metastore


  # metallogic-admin:
  #   image: yc3231996/metallogic-admin:latest
  #   build:
  #     context: ../webapp-admin
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./volumes/metallogic/admin:/app 





