include:
  - docker-compose-dify.yaml

services:
  metallogic-mockdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: datagpt
      POSTGRES_PASSWORD: datagpt
      POSTGRES_DB: datagpt
    volumes:
      - ./volumes/mockdb/data:/var/lib/postgresql/data

  metallogic-weaviate:
    image: semitechnologies/weaviate:1.19.0
    restart: always
    ports:
      - "8001:8080"
    volumes:
      - ./volumes/weaviate:/var/lib/weaviate
    env_file:
      - ./openai.env
    environment:
      OPENAI_APIKEY: ${OPENAI_APIKEY}
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "false"
      DEFAULT_VECTORIZER_MODULE: text2vec-openai
      ENABLE_MODULES: text2vec-openai
      CLUSTER_HOSTNAME: node1
      AUTHENTICATION_APIKEY_ENABLED: "true"
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
      AUTHENTICATION_APIKEY_USERS: datagpt
      AUTHORIZATION_ADMINLIST_ENABLED: "true"
      AUTHORIZATION_ADMINLIST_USERS: datagpt

  metallogic-api:
    image: yc3231996/metallogic-api:latest
    ports:
      - "8000:8000"
    volumes:
      - ./volumes/metallogic/api/metastore:/app/metastore
    environment:
      WEAVIATE_URL: http://metallogic-weaviate:8080
      WEAVIATE_API_KEY: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih

  # no need volumes, if want to mount a volume, make sure it doesn't override working directory
  metallogic-admin:
    image: yc3231996/metallogic-admin:latest
    ports:
      - "3000:3000"
    environment:
      API_BASE_URL: http://metallogic-api:8000
      API_KEY: p2QtZ91ujRN2db0OyVWPXmvmv7e9zQLBswOiL4REZcY